import { Metadata } from "next";
import { Poppins, Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { NotificationsProvider } from "@/Components/NotificationsContext/NotificationsContext";
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--poppins",
  weight: ["400", "500"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--inter",
  weight: ["700", "400"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--montserrat",
  weight: ["700", "400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="az">
      <body
        className={`${poppins.variable} ${inter.variable} ${montserrat.variable}`}
      >
        <NotificationsProvider>{children}</NotificationsProvider>
      </body>
    </html>
  );
}